/**
 * The TypeScript situation builder must reproduce, field for field, what
 * `scripts/calculator.py::create_situation` produces for the same household.
 * The expected situations are generated by Python and committed to
 * `__fixtures__/situations.json`; see scripts/tests/situation_fixtures.py.
 */

import { describe, expect, it } from 'vitest';
import fixtures from './__fixtures__/situations.json';
import stateInputs from '../../public/data/state_inputs.json';
import { buildSituation, type HouseholdSpec, type Situation } from './situation';
import type { StateInputsFile } from './types';

interface FixtureCase {
  id: string;
  inputs: {
    state: string;
    num_adults: number;
    child_ages: number[];
    earned_income?: number;
    monthly_charge_per_child?: number;
    hours_per_day?: number[];
    days_per_week?: number;
    attending_days_per_month?: number;
    in_activity?: boolean;
    person_inputs?: Record<string, string | number | boolean>;
    spm_inputs?: Record<string, string | number | boolean>;
  };
  situation: Situation;
}

const { year, cases } = fixtures as unknown as { year: number; cases: FixtureCase[] };
const configs = (stateInputs as StateInputsFile).states;

function toHousehold(inputs: FixtureCase['inputs']): HouseholdSpec {
  return {
    state: inputs.state,
    adults: inputs.num_adults,
    childAges: inputs.child_ages,
    income: inputs.earned_income ?? 0,
    monthlyChargePerChild: inputs.monthly_charge_per_child ?? 1500,
    hoursPerDay: inputs.hours_per_day,
    daysPerWeek: inputs.days_per_week ?? 5,
    attendingDaysPerMonth: inputs.attending_days_per_month ?? 22,
    inActivity: inputs.in_activity ?? true,
    personInputs: inputs.person_inputs,
    spmInputs: inputs.spm_inputs,
  };
}

/** The TypeScript builder also requests outputs as `{year: null}`; Python does not. */
function withoutRequestedOutputs(situation: Situation): Situation {
  const strip = <T extends Record<string, unknown>>(entity: T): T => {
    const copy: Record<string, unknown> = {};
    Object.entries(entity).forEach(([key, value]) => {
      const isNullRequest =
        value !== null &&
        typeof value === 'object' &&
        !Array.isArray(value) &&
        Object.values(value as Record<string, unknown>).every((v) => v === null);
      if (!isNullRequest) copy[key] = value;
    });
    return copy as T;
  };
  return {
    ...situation,
    people: Object.fromEntries(
      Object.entries(situation.people).map(([id, person]) => [id, strip(person)]),
    ),
    spm_units: { spm_unit: strip(situation.spm_units.spm_unit) },
  };
}

describe('buildSituation mirrors create_situation', () => {
  it('has fixture cases to check', () => {
    expect(cases.length).toBeGreaterThan(0);
  });

  cases.forEach((fixture) => {
    it(fixture.id, () => {
      const config = configs[fixture.inputs.state];
      expect(config, `no state_inputs entry for ${fixture.inputs.state}`).toBeDefined();
      const built = buildSituation(config, toHousehold(fixture.inputs), year);
      expect(withoutRequestedOutputs(built)).toEqual(fixture.situation);
    });
  });
});
